### ISSUE TITLE
Request for full code

### ISSUE THREAD

**Issue by Piyushi-0** [hdeplaen/uotod#1]
Dear Authors,
 
Nice work! Could you please let me know when the full code will be shared?

Thanks.
Piyushi

**Comment by hdeplaen** [comment]
Dear Piyushi,

We really wanted the code to be available for CVPR 2023, which is happening now. Unfortunately, we could not manage to finish it on time, and I would count on a month approximately. Please excuse us for the delay. Our code is very dirty and we are making a nice package with documentation in order for everyone to use it easily. 

In between, I can refer to the [Python Optimal Transport Toolbox](https://pythonot.github.io) library. Another alternative is to directly implement the scaling algorithms in [Appendix C.1](https://hdeplaen.github.io/uotod/docs/uotod_supp.pdf) of our paper, the algorithms are short and very similar to implement.

Best regards,

Henri

**Comment by Piyushi-0** [comment]
Dear Henri,
Thank you for the reply. While I am familiar with the OT codes, I haven't worked on object detection & would appreciate if you could share some references on how to integrate the OT loss in object detection codes.

Thanks & Regards,
Piyushi

**Comment by zhouxuexiao** [comment]
When will the complete code be released?

**Comment by zhouxuexiao** [comment]
Could you please let me know by when the full code will be shared?
